name: sim_companies
description: A starting point for Dart libraries or applications.
version: 1.0.0

environment:
  sdk: ^3.2.3

dependencies:
  decimal: ^2.3.3
  dio: ^5.4.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
